services:
  - type: web
    name: word-definition-lookup
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_USERNAME
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_CLUSTER
        sync: false
    autoDeploy: true
